document.addEventListener("DOMContentLoaded",function(){$("body").on("click",function(event){if(event.target.hasAttribute("data-toggle-menu")){let target=$("#"+event.target.getAttribute("data-toggle-menu"));if(target.hasClass("menu_toggled")){target.removeClass("menu_toggled");}else{$(".menu_toggled").not(target).removeClass("menu_toggled");target.addClass("menu_toggled");}}else if(document.querySelector(".menu_toggled")&&$(event.target).parents(".menu_toggled").length==0){$(".menu_toggled").removeClass("menu_toggled");}});});function showCategoryByLink(id,alternative=false){$(".ad_billboard").show();$(".home").hide();$(".all").empty();var url1="php/main.php?id="+id;var url2="php/main.php?id="+id+"&alternative="+alternative;$.ajax({url:(alternative==false)?url1:url2,type:'GET',dataType:'json',success:function(res){makeCardSection(res[0][0].replace(/\s+/g,'-').toLowerCase().replace("'",''),res[0][0]);for(var i=0;i<res[0][1].length;i++){console.log(res[0][1][i]);makeExploitCard(res[0][0].replace(/\s+/g,'-').toLowerCase().replace("'",''),res[0][1][i]["img_url"],res[0][1][i]["downloads"],res[0][1][i]["patchdate"],res[0][1][i]["title"],res[0][1][i]["short_description"],res[0][1][i]["alias"],res[0][1][i]["badge"]);if(res[0][1].length<=4){$('#more-'+res[0][0].replace(/\s+/g,'-').toLowerCase().replace("'",'')+'.section_more').hide();}}
for(var j=0;j<res[1].length;j++){if(res[1][j][0]){makeCardSection(res[1][j][0].replace(/\s+/g,'-').toLowerCase(),res[1][j][0]);}}
for(var j=0;j<res[1].length;j++){for(var i=0;i<res[1][j][1].length;i++){if(res[1][j][0]){makeExploitCard(res[1][j][0].replace(/\s+/g,'-').toLowerCase(),res[1][j][1][i]["img_url"],res[1][j][1][i]["downloads"],res[1][j][1][i]["patchdate"],res[1][j][1][i]["title"],res[1][j][1][i]["short_description"],res[1][j][1][i]["alias"],res[1][j][1][i]["badge"]);if(res[1][j][1].length<=4){$('#more-'+res[1][j][0].replace(/\s+/g,'-').toLowerCase().replace("'",'')+'.section_more').hide();}}}}
$('.section_more').click(function(event){$(this).text($(this).text()=='Show all \u25BC'?'Show less \u25B2':'Show all \u25BC');if(!$("#"+this.id.replace('more-','')+".cards_list").hasClass("cards_hidden")){$("#"+this.id.replace('more-','')+".cards_list").addClass("cards_hidden");}else{$("#"+this.id.replace('more-','')+".cards_list").removeClass("cards_hidden");}});}});}
function showAll(){$(".ad_billboard").show();$(".home").hide();$(".all").empty();$.ajax({url:"php/main.php",type:'GET',dataType:'json',success:function(res){for(var j=0;j<res.length;j++){makeCardSection(res[j][0][0].replace(/\s+/g,'-').toLowerCase().replace("'",''),res[j][0][0]);for(var i=0;i<res[j][0][1].length;i++){makeExploitCard(res[j][0][0].replace(/\s+/g,'-').toLowerCase().replace("'",''),res[j][0][1][i]["img_url"],res[j][0][1][i]["downloads"],res[j][0][1][i]["patchdate"],res[j][0][1][i]["title"],res[j][0][1][i]["short_description"],res[j][0][1][i]["alias"],res[j][0][1][i]["badge"]);if(res[j][0][1].length<=4){$('#more-'+res[j][0][0].replace(/\s+/g,'-').toLowerCase().replace("'",'')+'.section_more').hide();}}}
$('.section_more').click(function(event){$(this).text($(this).text()=='Show all \u25BC'?'Show less \u25B2':'Show all \u25BC');if(!$("#"+this.id.replace('more-','')+".cards_list").hasClass("cards_hidden")){$("#"+this.id.replace('more-','')+".cards_list").addClass("cards_hidden");}else{$("#"+this.id.replace('more-','')+".cards_list").removeClass("cards_hidden");}});}});}
function makeCardSection(id,title){var CardSection=` <div id="`+id+`" class="releases_section"> <div class="section_header"> <span class="general_title">`+title+`</span> <button id="more-`+id+`" class="section_more">Show all &#9660;</button>  </div> <div class="releases_cards"> <div id="`+id+`" class="cards_list cards_hidden"> </div> <ins class="adsbygoogle" style="display:inline-block;width:970px;height:90px" data-ad-client="ca-pub-2046708012782383" data-ad-slot="9295404159"></ins><script>(adsbygoogle=window.adsbygoogle || []).push({});</script> </div> </div>`;$('.all').append(CardSection);}
function makeExploitCardEasy(id,img,patchdate,title,description,alias,badge){var ExploitCard=' <div class="exploit_card" id="'+id+'"> '+badge+' <div class="card_header"> <img src="'+img+'" class="header_image"> <div class="header_details"> <div class="header_row"> <span class="header_tag"><i class="material-icons">update</i>'+patchdate+'</span>  </div> </div> </div> <div class="card_content"> <span class="card_title">'+title+'</span> <p class="card_details"> '+description+' </p> </div> <div class="card_actions"> <div class="actions_details"> <span class=""></span> </div> <button onclick="window.open(`/cheat/'+alias+'`, `_blank`);" class="actions_download"><i class="material-icons mirrorY">publish</i>Download</button> </div> </div>';$('#'+id+'.cards_list').append(ExploitCard);}
function makeExploitCard(id,img,downloads,patchdate,title,description,alias,badge){var ExploitCard=' <div class="exploit_card" id="'+id+'"> '+badge+' <div class="card_header"> <img src="'+img+'" class="header_image"> <div class="header_details"> <div class="header_row"> <span class="header_tag"><i class="material-icons">update</i>'+patchdate+'</span> <span class="header_tag"><span class="header_tag"><i class="material-icons mirrorY">publish</i>'+downloads+'</span> </div> </div> </div> <div class="card_content"> <span class="card_title">'+title+'</span> <p class="card_details"> '+description+' </p> </div> <div class="card_actions"> <div class="actions_details"> <span class=""></span> </div> <button onclick="window.location.href = `/cheat/'+alias+'`;" class="actions_download"><i class="material-icons mirrorY">publish</i>Download</button> </div> </div>';$('#'+id+'.cards_list').append(ExploitCard);}
function addUpvote(id){if(typeof Cookies.get('vote'+id)==='undefined'){Cookies.set("vote"+id,"up",{expires:365});$.get("/php/action.php?upvote="+id,function(data){$(".vote_amount.upvote").text(parseInt($(".vote_amount.upvote").html())+1).addClass("blue");$(".vote_choice.upvote").addClass("is-liked");gtag('event','cheat_upvoted',{'app_name':'cheatsquad.gg'});});}}
function addDownvote(id){if(typeof Cookies.get('vote'+id)==='undefined'){Cookies.set("vote"+id,"down",{expires:365});$.get("/php/action.php?downvote="+id,function(data){$(".vote_amount.downvote").text(parseInt($(".vote_amount.downvote").html())+1).addClass("blue");$(".vote_choice.downvote").addClass("is-liked");gtag('event','cheat_downvoted',{'app_name':'cheatsquad.gg'});});}}
function addDownload(id){if(typeof Cookies.get('download'+id)==='undefined'){Cookies.set("download"+id,true,{expires:365});$.get("/php/action.php?download="+id,function(data){gtag('event','cheat_downloaded',{'app_name':'cheatsquad.gg'});});}}
function warning(id,url){Swal.fire({title:`Everything is fine.`,html:`The cheat you are trying to download uses a process called injection to install itself to the game.<br><br>
    This process is also being used by some malicious software,
    which is why your antivirus tool may detects this download as malicious.<br><br>
    <b>We can guarantee you that it's a 100% safe to use.<b>`,type:`warning`,confirmButtonColor:`#3085d6`,confirmButtonText:`I understand, take me to the download.`}).then((result)=>{if(result.value){addDownload(id);window.open(url,'_blank');}})}
function isFile(pathname){return pathname.split('/').pop().indexOf('.')>-1;}
function back(id){if(id===1){cheat="minecraft";}else if(id===2){cheat="csgo";}else if(id===3){cheat="roblox";}else if(id===4){cheat="gmod";}else if(id===5){cheat="battlefield";}else if(id===6){cheat="gta";}else if(id===7){cheat="teamfortress";}else if(id===8){cheat="pubg";}else if(id===9){cheat="amongus";}else if(id===10){cheat="krunker";}else if(id===11){cheat="valorant";}else if(id===12){cheat="apex";}else if(id===13){cheat="fortnite";}else{cheat="other";}
window.location.href='/'+cheat;}
$('img[data-enlargable]').addClass('img-enlargable').click(function(){var src=$(this).attr('src');$('<div>').css({background:'RGBA(0,0,0,.5) url('+src+') no-repeat center',backgroundSize:'50% auto',width:'100%',height:'100%',position:'fixed',zIndex:'10000',top:'0',left:'0',cursor:'zoom-out'}).click(function(){$(this).remove();}).appendTo('body');});var e=document.createElement('div');e.id='dfwdoiwjedoiwedioj';e.style.display='none';document.body.appendChild(e);function lol(id,check,seek){if(Cookies.get("vote"+id)==="up"){$(".vote_amount.upvote").addClass("blue");$(".vote_choice.upvote").addClass("is-liked");}
if(Cookies.get("vote"+id)==="down"){$(".vote_amount.downvote").addClass("blue");$(".vote_choice.downvote").addClass("is-liked");}
if(document.getElementById("dfwdoiwjedoiwedioj")){$("."+seek).show();$("."+check).hide();}else{Swal.fire({type:"error",title:"Disable your adblocker!",html:"Please disable your adblocker to download.<br> We do not display any annoying ads. :)",showCancelButton:false,confirmButtonColor:"#3085d6",confirmButtonText:"I disabled it!",allowOutsideClick:false,allowEscapeKey:false,allowEnterKey:false,footer:`<a target=" _blank" href="https://help.eyeo.com/en/adblockplus/add-a-website-to-the-whitelist">How do I disable my adblocker for cheatsquad?</a>`}).then((result)=>{if(result.value){location.reload();}});$("."+seek).remove();}}